apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-management
  labels:
    app: transaction-management
spec:
  replicas: 3
  selector:
    matchLabels:
      app: transaction-management
  template:
    metadata:
      labels:
        app: transaction-management
    spec:
      containers:
      - name: transaction-management
        image: transaction-management:0.0.1-SNAPSHOT
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        env:
        - name: SPRING_REDIS_HOST
          value: "redis-service"
        - name: SPRING_REDIS_PORT
          value: "6379"